//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClubSystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ClusDBEntities : DbContext
    {
        public ClusDBEntities()
            : base("name=ClusDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sys_Function> sys_Function { get; set; }
        public virtual DbSet<t_f_activity> t_f_activity { get; set; }
        public virtual DbSet<t_f_finance> t_f_finance { get; set; }
        public virtual DbSet<t_f_meeting> t_f_meeting { get; set; }
        public virtual DbSet<t_f_news> t_f_news { get; set; }
        public virtual DbSet<t_f_Role> t_f_Role { get; set; }
        public virtual DbSet<t_f_User> t_f_User { get; set; }
        public virtual DbSet<t_f_User_Role> t_f_User_Role { get; set; }
        public virtual DbSet<sys_Role_Function> sys_Role_Function { get; set; }
    }
}
