//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClubSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_f_news
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public Nullable<System.DateTime> EditTime { get; set; }
        public Nullable<bool> isDel { get; set; }
        public string attachment { get; set; }
        public string option1 { get; set; }
        public string oprion2 { get; set; }
        public string option3 { get; set; }
        public string option4 { get; set; }
        public string option5 { get; set; }
    }
}
