//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClubSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_f_meeting
    {
        public int ID { get; set; }
        public Nullable<int> Club_ID { get; set; }
        public Nullable<int> Finance_ID { get; set; }
        public string Tittle { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public string Speaker { get; set; }
        public Nullable<int> joinman { get; set; }
        public Nullable<int> leaveman { get; set; }
        public string option1 { get; set; }
        public string option2 { get; set; }
        public string option3 { get; set; }
        public string option4 { get; set; }
        public string option5 { get; set; }
    }
}
